{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  {{- with (first .Values.istio.gateways) }}
  name:  {{ .name }}
  {{- end }}
spec:
  selector:
    istio: {{ .Values.istio.ingressController.name }}
  servers:
    - port:
        {{- with (first .Values.istio.gateways) }}
        number: {{ .port | default 443 }}
        name: {{ .portName | default "https" }}
        protocol: {{ .protocol | default "HTTPS" }}
        {{- end }}
      hosts:
        {{- include "common.tplvalues.render" ( dict "value" .Values.istio.hosts "context" $ ) | nindent 6 }}
  {{- end }}
